language: java
jdk:
- openjdk7
before_script:
 - chmod +x build-travis.sh
 - chmod +x bundle.sh
script:
- ./build-travis.sh
- ./bundle.sh $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  user: "alamarre"
  password: $GITHUB_PASS
  file: "maestro.zip"
  skip_cleanup: true
  on:
    repo: alamarre/maestro-media-center