language: java
jdk:
- oraclejdk8
before_script:
 - chmod +x build-travis.sh
 - chmod +x bundle.sh
script:
- ./build-travis.sh
- ./bundle.sh $TRAVIS_BUILD_NUMBER
deploy:
  provider: releases
  api-key: $GITHUB_KEY
  file: "maestro.zip"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
